version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: albertmontolio
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: images-transformer-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
