export const INJECTION_TOKENS = {
  IMAGE_CATEGORIZATION_QUEUE: Symbol('IMAGE_CATEGORIZATION_QUEUE'),
  IMAGE_TRANSFORMATION_QUEUE: Symbol('IMAGE_TRANSFORMATION_QUEUE'),
  IMAGE_DETECTION_QUEUE: Symbol('IMAGE_DETECTION_QUEUE'),
}; 